generic-service:
  nameOverride: hmpps-people-on-probation-ui
  productId: 'HMPPS518' # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  # the IRSA service account name for accessing AWS resources
  # serviceAccountName: "hmpps-people-on-probation-ui"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-people-on-probation-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-people-on-probation-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    AUDIT_SQS_REGION: 'eu-west-2'
    AUDIT_SERVICE_NAME: 'HMPPS518' # Your audit service name
    ONE_LOGIN_SCOPES: 'openid email phone'
    ONE_LOGIN_VTR: 'Cl.Cm'

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    # These secrets are created by terraform.
    hmpps-people-on-probation-ui-client-creds:
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'   
    hmpps-people-on-probation-ui-session-secret:
      SESSION_SECRET: 'SESSION_SECRET'
    hmpps-people-on-probation-ui-one-login:
      ONE_LOGIN_CLIENT_ID: 'ONE_LOGIN_CLIENT_ID'
      ONE_LOGIN_KEY_ID: 'ONE_LOGIN_KEY_ID'
      ONE_LOGIN_PRIVATE_KEY_BASE64: 'ONE_LOGIN_PRIVATE_KEY_BASE64'
      ONE_LOGIN_PUBLIC_KEY_BASE64: 'ONE_LOGIN_PUBLIC_KEY_BASE64'
    hmpps-people-on-probation-ui-elasticache-redis:
      REDIS_HOST: 'primary_endpoint_address'
      REDIS_AUTH_TOKEN: 'auth_token'
    hmpps-people-on-probation-ui-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-people-on-probation-ui-chatbot:
      POP_CHATBOT_API_KEY: "POP_CHATBOT_API_KEY"
    # This secret will need to be created in your namespace (note it isn't in hmpps-templates-dev)
    # IRSA configuration in your namespace will also be required, and then uncomment serviceAccountName above.
    # sqs-hmpps-audit-secret:
    #   AUDIT_SQS_QUEUE_URL: 'sqs_queue_url'

generic-prometheus-alerts:
  targetApplication: hmpps-people-on-probation-ui
