---
# Per environment values which override defaults in hmpps-people-on-probation-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: people-on-probation-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://people-on-probation-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    PEOPLE_ON_PROBATION_API_URL: 'https://people-on-probation-api-dev.hmpps.service.justice.gov.uk'
    POP_CHATBOT_API_URL: 'https://probationchatbot-production.up.railway.app/chatbot/chat-embed'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-people-on-probation-nonprod
