---
# Per environment values which override defaults in hmpps-people-on-probation-ui/values.yaml

generic-service:
  ingress:
    host: people-on-probation.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://people-on-probation-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    PEOPLE_ON_PROBATION_API_URL: 'https://people-on-probation-api.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-people-on-probation
