---
# Per environment values which override defaults in hmpps-people-on-probation-ui/values.yaml

generic-service:
  ingress:
    host: probation-account.hmpps.service.justice.gov.uk
    className: modsec

  env:
    INGRESS_URL: "https://probation-account.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    ONE_LOGIN_ISSUER_URL: "https://oidc.account.gov.uk"
    PEOPLE_ON_PROBATION_API_URL: "https://people-on-probation-api.hmpps.service.justice.gov.uk"
    ONE_LOGIN_REDIRECT_URI: "https://probation-account.hmpps.service.justice.gov.uk/sign-in/callback"
    ONE_LOGIN_POST_LOGOUT_REDIRECT_URI: "https://probation-account.hmpps.service.justice.gov.uk"
    AUDIT_ENABLED: "false"
    POP_CHATBOT_API_URL: "https://probationchatbot-production.up.railway.app/chatbot/chat-embed"

generic-prometheus-alerts:
  alertSeverity: hmpps-people-on-probation
